% Create a invertedFcoplanar antenna
% Generated by MATLAB(R) 9.13 and Antenna Toolbox 5.3.
% Generated on: 26-Jan-2023 03:07:05

%% Antenna Properties 

F0 = 2.4e9;

antennaObject = design(invertedFcoplanar, F0);
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 

% Define frequency range 
freqRange = linspace(2.2e9, 2.6e9, 21);
figure;
impedance(antennaObject, freqRange)
% sparameter
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, F0)

%% Generating PCB

pcbAntenna = pcbStack(antennaObject);
pcbAntenna.BoardThickness = 1e-3;

d1 = dielectric('FR4');
d1.EpsilonR = 4.5;
d1.Thickness = 1e-3;
pcbAntenna.Layers{2} = d1;
show(pcbAntenna)